name: "Terraform action"
on: 
  push:
    branches:
      -main
  # workflow_dispatch:
  #   inputs:
  #     config:
  #       description: 'Terraform Config to apply(config1 or config2)'
  #       required: true
  #       default: 'config2'
jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps: 
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: github-workflow-s3-access 

    - name: Initialize Terraform
      env: 
        AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
        AWS_BUCKET_KEY_NAME: ${{secrets.AWS_BUCKET_KEY_NAME}}
      run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}"
      working-directory: WK2/TASK1

    - name: Terraform plan
      id: plan
      run: terraform plan
      continue-on-error: false

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: WK2/TASK1

    


    